version: 2.1
jobs:
  Publish-to-Pages:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      # Run your project's build step
      - run: npm install && npm run build
      # Publish with wrangler
      - run: npx wrangler pages publish dist --project-name=Yamss
        environment:
          CLOUDFLARE_ACCOUNT_ID: CLOUDFLARE_ACCOUNT_ID
          CLOUDFLARE_API_TOKEN: CLOUDFLARE_API_TOKEN

workflows:
  Publish-to-Pages-workflow:
    jobs:
      - Publish-to-Pages
