name: GitHub Actions Pages Publish
on: [push]
jobs:
  pages-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 16 is default, but lets make sure
      - name: Install Wrangler2 globally
        run: npm install -g wrangler@beta
      - name: Install dependencies
        run: npm install 
      - name: Build project
        run: npm run build
      - name: List files in the dist directory
        run: |
          ls ${{ github.workspace }}/dist
      - name: Check Wrangler version
        run: wrangler --version
      #- name: Pages publish
      #  run: wrangler pages publish